### ISSUE TITLE
List desynchronization detected!

### ISSUE THREAD

**Issue by Kahldris** [starik222/BooruDatasetTagManager#161] opened 2024-09-06 13:16 UTC
The thread it told me to go to was marked closed but I've had several crashes trying to use this program so far with this error. I have to save after every single image now, very frustrating. I don't think I did anything weird, just trying to add tags, but sometimes I fumble with the keybinds (my hand is getting sore from ctrl e).

(Not a bug but I also lost a lot of progress by UI confusion/user error before, I clicked 'set current tag to all images' thinking it would just ADD the actual currently selected SINGLE tag to all images' tag lists, instead it REPLACED all images' tags with ALL the tags on the current picture... and undo couldn't undo it *cries*)

[ErrorData.json](https://github.com/user-attachments/files/16908385/ErrorData.json)
![image](https://github.com/user-attachments/assets/23ac7645-219f-4939-b5ca-4e45d933b051)
![image](https://github.com/user-attachments/assets/a1749a53-e18b-4979-ab8f-08bab7bb5c42)

### Discussed in https://github.com/starik222/BooruDatasetTagManager/discussions/111

<div type='discussions-op-text'>

<sup>Originally posted by **starik222** January 11, 2024</sup>
This topic was created to post logs created when the "List desynchronization detected!" error occurred. You need to attach the "ErrorData.json" file from the program folder and, if possible, describe what actions caused this error.</div>

**Comment by starik222** [comment] 2024-10-05 19:07
Are you using the latest version of the program? This error has been fixed and there have been no other error messages except yours. If you are indeed using the latest version of the program, please send me some more ErrorData.json, as I can't figure out the cause of the error yet.
If you find the current keyboard shortcuts inconvenient, you can reconfigure them for yourself in the settings menu.

**Comment by starik222** [comment] 2024-10-17 07:18
Not confirmed.

**Comment by starik222** [comment] 2024-10-23 07:09
Fixed in [2.3.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.3.1)

**Closed by starik222** 2024-10-23 07:09 UTC
